// 由 tools/icons/gen_icons.py 生成 —— 不要手改（改图标请改生成脚本再跑一次）。
//
// 图标字体：Phosphor Icons (Regular) —— MIT License, https://phosphoricons.com
// 字体文件：client/assets/fonts/Phosphor.ttf（原样分发）
//
// 用法：ImGui::Text("%s 设备", go2::icon::Robot);
// 说明：字形以 UTF-8 字节转义写死 —— 不依赖编译器对 \\uXXXX 的编码实现。
#pragma once

namespace go2 {
namespace icon {

inline constexpr const char* CaretLeft     = "\xEE\x84\xB8";  // 返回 / 左转  (caret-left U+E138)
inline constexpr const char* CaretDown     = "\xEE\x84\xB6";  // 后退（向下）  (caret-down U+E136)
inline constexpr const char* CaretRight    = "\xEE\x84\xBA";  // 右转  (caret-right U+E13A)
inline constexpr const char* X             = "\xEE\x93\xB6";  // 关闭  (x U+E4F6)
inline constexpr const char* Check         = "\xEE\x86\x82";  // 勾选  (check U+E182)
inline constexpr const char* Pencil        = "\xEE\x8E\xB4";  // 编辑  (pencil-simple U+E3B4)
inline constexpr const char* Robot         = "\xEE\x9D\xA2";  // 设备 / 机器狗  (robot U+E762)
inline constexpr const char* Dog           = "\xEE\x9D\x8A";  // 机器狗  (dog U+E74A)
inline constexpr const char* Paw           = "\xEE\x99\x88";  // 脚印 / 狗爪  (paw-print U+E648)
inline constexpr const char* User          = "\xEE\x93\x82";  // 单控  (user U+E4C2)
inline constexpr const char* Users         = "\xEE\x9A\x8E";  // 群控  (users-three U+E68E)
inline constexpr const char* Gear          = "\xEE\x89\xB2";  // 设置  (gear-six U+E272)
inline constexpr const char* Log           = "\xEE\x8B\xB4";  // 日志  (list-dashes U+E2F4)
inline constexpr const char* List          = "\xEE\x8B\xB0";  // 列表  (list U+E2F0)
inline constexpr const char* Estop         = "\xEE\x8E\x8E";  // 急停  (octagon U+E38E)
inline constexpr const char* Siren         = "\xEE\xA6\xB8";  // 急停（备用）  (siren U+E9B8)
inline constexpr const char* Joystick      = "\xEE\xA9\x9E";  // 遥控  (joystick U+EA5E)
inline constexpr const char* Gamepad       = "\xEE\x89\xAE";  // 手柄  (game-controller U+E26E)
inline constexpr const char* TaiChi        = "\xEE\xB5\x9C";  // 倒立 / 摆姿势  (person-simple-tai-chi U+ED5C)
inline constexpr const char* Eye           = "\xEE\x88\xA0";  // 隐私 / 可见  (eye U+E220)
inline constexpr const char* EyeOff        = "\xEE\x88\xA4";  // 隐藏 IP  (eye-slash U+E224)
inline constexpr const char* Key           = "\xEE\x8B\x96";  // 钥匙库  (key U+E2D6)
inline constexpr const char* Refresh       = "\xEE\x82\x94";  // 刷新 / 重扫  (arrows-clockwise U+E094)
inline constexpr const char* Fullscreen    = "\xEE\x82\xA6";  // 全屏  (arrows-out-simple U+E0A6)
inline constexpr const char* Dots          = "\xEE\x87\xBE";  // 更多  (dots-three U+E1FE)
inline constexpr const char* Search        = "\xEE\x8C\x8C";  // 查询 / 状态  (magnifying-glass U+E30C)
inline constexpr const char* Thermometer   = "\xEE\x97\x86";  // 温度  (thermometer U+E5C6)
inline constexpr const char* Wifi          = "\xEE\x93\xAA";  // 网络  (wifi-high U+E4EA)
inline constexpr const char* Battery       = "\xEE\x83\x80";  // 电量 / 续航  (battery-full U+E0C0)
inline constexpr const char* Charging      = "\xEE\x82\xBA";  // 充电  (battery-charging U+E0BA)
inline constexpr const char* Camera        = "\xEE\x84\x8E";  // 相机  (camera U+E10E)
inline constexpr const char* Video         = "\xEE\x93\x9A";  // 录像  (video-camera U+E4DA)
inline constexpr const char* Record        = "\xEE\x8F\xAE";  // 录制  (record U+E3EE)
inline constexpr const char* Stop          = "\xEE\x91\xAC";  // 停止  (stop U+E46C)
inline constexpr const char* Speaker       = "\xEE\x91\x8A";  // 音量  (speaker-high U+E44A)
inline constexpr const char* Lamp          = "\xEE\x98\xB8";  // 灯光  (lamp U+E638)
inline constexpr const char* Broadcast     = "\xEE\x83\xB2";  // 雷达 / 广播  (broadcast U+E0F2)
inline constexpr const char* Monitor       = "\xEE\x8C\xAE";  // 图传  (monitor U+E32E)
inline constexpr const char* Crosshair     = "\xEE\x87\x96";  // 定位  (crosshair U+E1D6)
inline constexpr const char* Flag          = "\xEE\x89\x84";  // 标记  (flag U+E244)
inline constexpr const char* Jump          = "\xEE\xAB\x82";  // 跳 / 跳跃跑  (rabbit U+EAC2)
inline constexpr const char* Flip          = "\xEE\xB5\xAA";  // 翻身 / 空翻  (flip-horizontal U+ED6A)
inline constexpr const char* Throw         = "\xEE\x9C\xB2";  // 扑人  (person-simple-throw U+E732)
inline constexpr const char* HeartHand     = "\xEE\xA0\x90";  // 比心  (hand-heart U+E810)
inline constexpr const char* Handshake     = "\xEE\x96\x82";  // 握手  (handshake U+E582)
inline constexpr const char* Wave          = "\xEE\x96\x80";  // 打招呼  (hand-waving U+E580)
inline constexpr const char* Pray          = "\xEE\xB3\x88";  // 拜年  (hands-praying U+ECC8)
inline constexpr const char* Clap          = "\xEE\x9A\xA0";  // 鼓掌  (hands-clapping U+E6A0)
inline constexpr const char* Music         = "\xEE\x8D\x80";  // 舞蹈  (music-notes U+E340)
inline constexpr const char* Confetti      = "\xEE\xA0\x9A";  // 庆祝  (confetti U+E81A)
inline constexpr const char* Boot          = "\xEE\xB3\x8A";  // 太空步  (boot U+ECCA)
inline constexpr const char* Sneaker       = "\xEE\xB5\xA0";  // 交叉步  (sneaker-move U+ED60)
inline constexpr const char* Footprints    = "\xEE\xAA\x88";  // 并腿跑  (footprints U+EA88)
inline constexpr const char* Chair         = "\xEE\x80\x92";  // 坐下  (armchair U+E012)
inline constexpr const char* Stretch       = "\xEE\xB3\xBE";  // 伸懒腰  (person-arms-spread U+ECFE)
inline constexpr const char* Person        = "\xEE\x8E\xA8";  // 直立 / 站立  (person U+E3A8)
inline constexpr const char* PersonSimple  = "\xEE\x9C\xAE";  // 常规  (person-simple U+E72E)
inline constexpr const char* Walk          = "\xEE\x9C\xBA";  // 行走 / 跟随  (person-simple-walk U+E73A)
inline constexpr const char* Run           = "\xEE\x9C\xB0";  // 跑步 / 小跑  (person-simple-run U+E730)
inline constexpr const char* Hike          = "\xEE\xB5\x94";  // 前跳（备用）  (person-simple-hike U+ED54)
inline constexpr const char* Lock          = "\xEE\x8C\x88";  // 阻尼 / 锁定  (lock-simple U+E308)
inline constexpr const char* LockOpen      = "\xEE\x8C\x8A";  // 解锁  (lock-simple-open U+E30A)
inline constexpr const char* Gauge         = "\xEE\x98\xA8";  // 档位 / 阻尼  (gauge U+E628)
inline constexpr const char* Sliders       = "\xEE\x90\xB4";  // 高度 / 步态  (sliders-horizontal U+E434)
inline constexpr const char* ArrowsLR      = "\xEE\x82\xA0";  // 左右  (arrows-left-right U+E0A0)
inline constexpr const char* ArrowsOut     = "\xEE\x82\xA4";  // 全向  (arrows-out-cardinal U+E0A4)
inline constexpr const char* ArrowsIn      = "\xEE\x94\xB2";  // 压缩 / 阻尼  (arrows-in-line-vertical U+E532)
inline constexpr const char* Lasso         = "\xEE\xB7\x86";  // 牵引  (lasso U+EDC6)
inline constexpr const char* Link          = "\xEE\x8B\xA2";  // 连接  (link U+E2E2)
inline constexpr const char* Sparkle       = "\xEE\x9A\xA2";  // 灵动  (sparkle U+E6A2)
inline constexpr const char* Lightning     = "\xEE\x8B\x9E";  // 暴走 / 高能  (lightning U+E2DE)
inline constexpr const char* Fire          = "\xEE\x89\x82";  // 加速  (fire U+E242)
inline constexpr const char* Wind          = "\xEE\x97\x92";  // 风速  (wind U+E5D2)
inline constexpr const char* Shuffle       = "\xEE\x90\xA2";  // 闪避  (shuffle U+E422)
inline constexpr const char* Crown         = "\xEE\x98\x94";  // 经典  (crown U+E614)
inline constexpr const char* Medal         = "\xEE\x8C\xA0";  // 奖章  (medal U+E320)
inline constexpr const char* Star          = "\xEE\x91\xAA";  // 收藏 / 星标  (star U+E46A)
inline constexpr const char* Shield        = "\xEE\x90\x8C";  // 安全 / 防护  (shield-check U+E40C)
inline constexpr const char* Sun           = "\xEE\x96\xB6";  // 日光  (sun-horizon U+E5B6)
inline constexpr const char* Stairs        = "\xEE\xA3\xAC";  // 台阶  (stairs U+E8EC)
inline constexpr const char* Cube          = "\xEE\x87\x9A";  // 模型  (cube U+E1DA)
inline constexpr const char* Scales        = "\xEE\x9D\x90";  // 平衡站立（天平=平衡）  (scales U+E750)
inline constexpr const char* Bed           = "\xEE\x83\x8C";  // 趴下（躺下）  (bed U+E0CC)
inline constexpr const char* ChairSimple   = "\xEE\xA5\x90";  // 坐下（椅子）  (chair U+E950)
inline constexpr const char* Compass       = "\xEE\x87\x88";  // 姿态角（方向/角度）  (compass U+E1C8)
inline constexpr const char* Infinity      = "\xEE\x98\xB4";  // 持续步态（∞ 持续）  (infinity U+E634)
inline constexpr const char* Coins         = "\xEE\x9E\x8E";  // 经济步态（省钱）  (coins U+E78E)
inline constexpr const char* Smiley        = "\xEE\x90\xB6";  // 满意（笑脸）  (smiley U+E436)
inline constexpr const char* MusicNote     = "\xEE\x8C\xBC";  // 舞蹈 1（单音符）  (music-note U+E33C)
inline constexpr const char* WaveSine      = "\xEE\xAA\x9A";  // 扭屁股（扭动）  (wave-sine U+EA9A)
inline constexpr const char* ArrowClockwise = "\xEE\x80\xB6";  // 前空翻（向前滚翻）  (arrow-clockwise U+E036)
inline constexpr const char* ArrowCounter  = "\xEE\x80\xB8";  // 后空翻（向后滚翻）  (arrow-counter-clockwise U+E038)
inline constexpr const char* BendDoubleUpLeft = "\xEE\x80\xBA";  // 左空翻  (arrow-bend-double-up-left U+E03A)
inline constexpr const char* BendDoubleUpRight = "\xEE\x80\xBC";  // 右空翻  (arrow-bend-double-up-right U+E03C)
inline constexpr const char* ArrowFatUp    = "\xEE\x94\xAE";  // 抬腿高度（向上抬）  (arrow-fat-up U+E52E)
inline constexpr const char* ArrowUp       = "\xEE\x82\x8E";  // 起立（兼容）  (arrow-up U+E08E)
inline constexpr const char* ArrowUUpLeft  = "\xEE\x82\x8A";  // 后仰站立（向后仰）  (arrow-u-up-left U+E08A)
inline constexpr const char* ArrowsOutLineV = "\xEE\x94\xB6";  // 机身高度（上下撑开）  (arrows-out-line-vertical U+E536)
inline constexpr const char* Ruler         = "\xEE\x9A\xB8";  // 量高度（查尺寸）  (ruler U+E6B8)
inline constexpr const char* Speedometer   = "\xEE\xB9\xB4";  // 速度档位（速度表）  (speedometer U+EE74)
inline constexpr const char* Pulse         = "\xEE\x80\x80";  // 运动状态（脉搏）  (pulse U+E000)
inline constexpr const char* FirstAid      = "\xEE\x95\xAE";  // 自动恢复（急救）  (first-aid U+E56E)
inline constexpr const char* Path          = "\xEE\x8E\x9C";  // 轨迹跟随（路径）  (path U+E39C)
inline constexpr const char* Wrench        = "\xEE\x97\x94";  // 设置自动恢复（扳手）  (wrench U+E5D4)
inline constexpr const char* WarningCircle = "\xEE\x93\xA2";  // 避障模式（注意障碍）  (warning-circle U+E4E2)
inline constexpr const char* Lifebuoy      = "\xEE\x98\xBA";  // 恢复站立（救生圈）  (lifebuoy U+E63A)
inline constexpr const char* HandPalm      = "\xEE\x95\xBE";  // 停止移动（手势停）  (hand-palm U+E57E)
inline constexpr const char* HeartStraight = "\xEE\x8A\xAA";  // 撒娇（卖萌）  (heart-straight U+E2AA)

}  // namespace icon
}  // namespace go2
