// 由 tools/icons/gen_icons.py 生成 —— 不要手改（改图标请改生成脚本再跑一次）。
//
// 两套图标，各司其职：
//   Phosphor Icons (MIT, https://phosphoricons.com) —— **界面框架**
//     client/assets/fonts/Phosphor.ttf (Regular) / Phosphor-Bold.ttf (Bold)
//   TianshuGo2 —— **动作图标**（宇树官方 App「天树探界遥控」的人形动作剪影）
//     client/assets/fonts/TianshuGo2.ttf
//
// ★ 动作图标为什么要单独一套：人形剪影能**一眼读出在做什么动作**
//   （站立/坐下/拜年/翻滚/倒立…），而抽象符号（天平=平衡、床=趴下、相机=摆姿势）
//   读不出来 —— 那正是旧动作图标"廉价感"的根源。Phosphor 之类开源库没有这类剪影。
//
// ★ Phosphor Regular 与 Bold 的码点完全一致（1530 个逐一核对，零错位），
//   所以切字重只是换一份 ImFont，字形字符串不变 —— 表里不必记字重。
//   TianshuGo2 只有单字重（剪影本身是实心块，加粗无意义）。
//
// 用法：
//   界面框架：ImGui::Text("%s 设备", go2::icon::Robot);
//   动作图标：drawActionIcon(dl, a, c, s, col);  // 见 ui_actions.cpp
// 说明：字形以 UTF-8 字节转义写死 —— 不依赖编译器对 \\uXXXX 的编码实现。
#pragma once

namespace go2 {
namespace icon {

inline constexpr const char* ArrowUp             = "\xEE\x82\x8E";  // 前进（D-pad 向上）  (arrow-up U+E08E)
inline constexpr const char* ArrowDown           = "\xEE\x80\xBE";  // 后退（D-pad 向下）  (arrow-down U+E03E)
inline constexpr const char* ArrowLeft           = "\xEE\x81\x98";  // 左转（D-pad 向左）  (arrow-left U+E058)
inline constexpr const char* ArrowRight          = "\xEE\x81\xAC";  // 右转（D-pad 向右）  (arrow-right U+E06C)
inline constexpr const char* CaretLeft           = "\xEE\x84\xB8";  // 返回  (caret-left U+E138)
inline constexpr const char* CaretDown           = "\xEE\x84\xB6";  // 下移 / 收起  (caret-down U+E136)
inline constexpr const char* CaretRight          = "\xEE\x84\xBA";  // 向前  (caret-right U+E13A)
inline constexpr const char* CaretUp             = "\xEE\x84\xBC";  // 上移 / 展开  (caret-up U+E13C)
inline constexpr const char* X                   = "\xEE\x93\xB6";  // 关闭  (x U+E4F6)
inline constexpr const char* Check               = "\xEE\x86\x82";  // 勾选  (check U+E182)
inline constexpr const char* Pencil              = "\xEE\x8E\xB4";  // 编辑  (pencil-simple U+E3B4)
inline constexpr const char* Robot               = "\xEE\x9D\xA2";  // 设备 / 机器狗  (robot U+E762)
inline constexpr const char* Dog                 = "\xEE\x9D\x8A";  // 机器狗  (dog U+E74A)
inline constexpr const char* Paw                 = "\xEE\x99\x88";  // 脚印 / 狗爪  (paw-print U+E648)
inline constexpr const char* User                = "\xEE\x93\x82";  // 单控  (user U+E4C2)
inline constexpr const char* Users               = "\xEE\x9A\x8E";  // 群控  (users-three U+E68E)
inline constexpr const char* Gear                = "\xEE\x89\xB2";  // 设置  (gear-six U+E272)
inline constexpr const char* Log                 = "\xEE\x91\xBE";  // 日志（终端输出）  (terminal U+E47E)
inline constexpr const char* List                = "\xEE\x91\xA4";  // 动作库（动作卡片网格）  (squares-four U+E464)
inline constexpr const char* Estop               = "\xEE\xA6\xB8";  // 急停（警报，最强信号）  (siren U+E9B8)
inline constexpr const char* Stop                = "\xEE\x91\xAC";  // 停止  (stop U+E46C)
inline constexpr const char* Lock                = "\xEE\x8C\x88";  // 锁定 / 阻尼  (lock-simple U+E308)
inline constexpr const char* LockOpen            = "\xEE\x8C\x8A";  // 解锁  (lock-simple-open U+E30A)
inline constexpr const char* Joystick            = "\xEE\xA9\x9E";  // 遥控  (joystick U+EA5E)
inline constexpr const char* Gamepad             = "\xEE\x89\xAE";  // 手柄  (game-controller U+E26E)
inline constexpr const char* Eye                 = "\xEE\x88\xA0";  // 可见  (eye U+E220)
inline constexpr const char* EyeOff              = "\xEE\x88\xA4";  // 隐藏 IP  (eye-slash U+E224)
inline constexpr const char* Key                 = "\xEE\x8B\x96";  // 钥匙库  (key U+E2D6)
inline constexpr const char* Refresh             = "\xEE\x82\x94";  // 刷新 / 重扫  (arrows-clockwise U+E094)
inline constexpr const char* Fullscreen          = "\xEE\x82\xA6";  // 全屏  (arrows-out-simple U+E0A6)
inline constexpr const char* Dots                = "\xEE\x87\xBE";  // 更多  (dots-three U+E1FE)
inline constexpr const char* Search              = "\xEE\x8C\x8C";  // 查询 / 搜索  (magnifying-glass U+E30C)
inline constexpr const char* Thermometer         = "\xEE\x97\x86";  // 温度  (thermometer U+E5C6)
inline constexpr const char* Wifi                = "\xEE\x93\xAA";  // 网络  (wifi-high U+E4EA)
inline constexpr const char* Battery             = "\xEE\x83\x80";  // 电量  (battery-full U+E0C0)
inline constexpr const char* Charging            = "\xEE\x82\xBA";  // 充电  (battery-charging U+E0BA)
inline constexpr const char* Link                = "\xEE\x8B\xA2";  // 连接  (link U+E2E2)
inline constexpr const char* Monitor             = "\xEE\x8C\xAE";  // 图传  (monitor U+E32E)
inline constexpr const char* Crosshair           = "\xEE\x87\x96";  // 定位 / 瞄准  (crosshair U+E1D6)
inline constexpr const char* Warning             = "\xEE\x93\xA2";  // 注意 / 避障  (warning-circle U+E4E2)
inline constexpr const char* Wrench              = "\xEE\x97\x94";  // 设置 / 修复  (wrench U+E5D4)
inline constexpr const char* FirstAid            = "\xEE\x95\xAE";  // 急救 / 恢复  (first-aid U+E56E)
inline constexpr const char* CaretUpDown         = "\xEE\x85\x80";  // 上下切换  (caret-up-down U+E140)
inline constexpr const char* Scales              = "\xEE\x9D\x90";  // 平衡站立（天平 = 平衡）  (scales U+E750)
inline constexpr const char* Bed                 = "\xEE\x83\x8C";  // 趴下（躺下）  (bed U+E0CC)
inline constexpr const char* Chair               = "\xEE\x80\x92";  // 起立（扶手椅 = 从坐姿起身）  (armchair U+E012)
inline constexpr const char* ChairSimple         = "\xEE\xA5\x90";  // 坐下（椅子）  (chair U+E950)
inline constexpr const char* Person              = "\xEE\x8E\xA8";  // 站立（人形）  (person U+E3A8)
inline constexpr const char* PersonSimple        = "\xEE\x9C\xAE";  // 常规姿态  (person-simple U+E72E)
inline constexpr const char* ArrowUUpLeft        = "\xEE\x82\x8A";  // 恢复站立（起身箭头）  (arrow-u-up-left U+E08A)
inline constexpr const char* HandPalm            = "\xEE\x95\xBE";  // 停止移动（举手示意停）  (hand-palm U+E57E)
inline constexpr const char* ArrowsIn            = "\xEE\x94\xB2";  // 阻尼（向内收 / 软腿）  (arrows-in-line-vertical U+E532)
inline constexpr const char* Compass             = "\xEE\x87\x88";  // 姿态角（罗盘）  (compass U+E1C8)
inline constexpr const char* Shuffle             = "\xEE\x90\xA2";  // 切换步态  (shuffle U+E422)
inline constexpr const char* Sliders             = "\xEE\x90\xB4";  // 机身高度（滑杆）  (sliders-horizontal U+E434)
inline constexpr const char* ArrowsOutLineV      = "\xEE\x94\xB6";  // 抬腿高度（上下撑开）  (arrows-out-line-vertical U+E536)
inline constexpr const char* Gauge               = "\xEE\x98\xA8";  // 档位 / 仪表  (gauge U+E628)
inline constexpr const char* Speedometer         = "\xEE\xB9\xB4";  // 速度档位（速度表）  (speedometer U+EE74)
inline constexpr const char* Infinity            = "\xEE\x98\xB4";  // 持续步态（∞ 持续）  (infinity U+E634)
inline constexpr const char* Coins               = "\xEE\x9E\x8E";  // 经济步态（省钱）  (coins U+E78E)
inline constexpr const char* Footprints          = "\xEE\xAA\x88";  // 静态行走（脚印）  (footprints U+EA88)
inline constexpr const char* Ruler               = "\xEE\x9A\xB8";  // 查机身高度  (ruler U+E6B8)
inline constexpr const char* ArrowFatUp          = "\xEE\x94\xAE";  // 查抬腿高度（向上抬）  (arrow-fat-up U+E52E)
inline constexpr const char* Pulse               = "\xEE\x80\x80";  // 查运动状态（脉搏）  (pulse U+E000)
inline constexpr const char* Path                = "\xEE\x8E\x9C";  // 轨迹跟随（路径）  (path U+E39C)
inline constexpr const char* Wave                = "\xEE\x96\x80";  // 打招呼（挥手）  (hand-waving U+E580)
inline constexpr const char* Stretch             = "\xEE\xB3\xBE";  // 伸懒腰（张开双臂）  (person-arms-spread U+ECFE)
inline constexpr const char* Smiley              = "\xEE\x90\xB6";  // 满意（笑脸）  (smiley U+E436)
inline constexpr const char* HeartStraight       = "\xEE\x8A\xAA";  // 撒娇（卖萌）  (heart-straight U+E2AA)
inline constexpr const char* MusicNote           = "\xEE\x8C\xBC";  // 舞蹈 1（单音符）  (music-note U+E33C)
inline constexpr const char* Music               = "\xEE\x8D\x80";  // 舞蹈 2（双音符）  (music-notes U+E340)
inline constexpr const char* Camera              = "\xEE\x84\x8E";  // 相机 / 摆姿势  (camera U+E10E)
inline constexpr const char* Pray                = "\xEE\xB3\x88";  // 拜年（作揖）  (hands-praying U+ECC8)
inline constexpr const char* WaveSine            = "\xEE\x9B\x9E";  // 扭屁股（多波峰 = 摆动的体感；wave-sine 单线太弱看不出在扭）  (waves U+E6DE)
inline constexpr const char* HeartHand           = "\xEE\xA0\x90";  // 比心（手比心）  (hand-heart U+E810)
inline constexpr const char* Boot                = "\xEE\xB3\x8A";  // 太空步（靴子后滑）  (boot U+ECCA)
inline constexpr const char* Stairs              = "\xEE\xA3\xAC";  // 单边踏步（台阶）  (stairs U+E8EC)
inline constexpr const char* Sneaker             = "\xEE\xB5\xA0";  // 交叉步（交叉的脚）  (sneaker-move U+ED60)
inline constexpr const char* Star                = "\xEE\x91\xAA";  // 站立展示（亮相星标）  (star U+E46A)
inline constexpr const char* Flag                = "\xEE\x89\x84";  // 领航跟随（旗）  (flag U+E244)
inline constexpr const char* Walk                = "\xEE\x9C\xBA";  // 自由行走  (person-simple-walk U+E73A)
inline constexpr const char* Run                 = "\xEE\x9C\xB0";  // 小跑  (person-simple-run U+E730)
inline constexpr const char* Crown               = "\xEE\x98\x94";  // 经典步态  (crown U+E614)
inline constexpr const char* ArrowsLR            = "\xEE\x82\xA0";  // 横向行走（左右）  (arrows-left-right U+E0A0)
inline constexpr const char* ArrowsOut           = "\xEE\x82\xA4";  // 自由跳跃（不限定方向）  (arrows-out-cardinal U+E0A4)
inline constexpr const char* Jump                = "\xEE\xAB\x82";  // 前跳（蹦跳）  (rabbit U+EAC2)
inline constexpr const char* Throw               = "\xEE\x9C\xB2";  // 前扑（身体前扑）  (person-simple-throw U+E732)
inline constexpr const char* ArrowClockwise      = "\xEE\x80\xB6";  // 前空翻（向前滚翻）  (arrow-clockwise U+E036)
inline constexpr const char* BendDoubleUpLeft    = "\xEE\x80\xBA";  // 左空翻（翻向左侧）  (arrow-bend-double-up-left U+E03A)
inline constexpr const char* BendDoubleUpRight   = "\xEE\x80\xBC";  // 右空翻（翻向右侧）  (arrow-bend-double-up-right U+E03C)
inline constexpr const char* ArrowCounter        = "\xEE\x80\xB8";  // 后空翻（向后滚翻）  (arrow-counter-clockwise U+E038)
inline constexpr const char* TaiChi              = "\xEE\xB5\x9C";  // 倒立（倒立人形）  (person-simple-tai-chi U+ED5C)
inline constexpr const char* Lightning           = "\xEE\x8B\x9E";  // 跳跃奔跑（迅捷）  (lightning U+E2DE)
inline constexpr const char* Fire                = "\xEE\x89\x82";  // 高能 / 爆发  (fire U+E242)
inline constexpr const char* Wind                = "\xEE\x97\x92";  // 风速  (wind U+E5D2)
inline constexpr const char* Shield              = "\xEE\x90\x8C";  // 自由避障（防护）  (shield-check U+E40C)

// ---- 天树动作图标（TianshuGo2 字体，U+E100 起；无字重概念）----
// 码点由 tools/icons/svg2font.py 从 SVG 转字体时写死，顺序即 SVG 文件名排序。
namespace ts {
inline constexpr const char* a_blowKiss                         = "\xEE\x84\x80";  // icon_active_blowKiss  (U+E100)
inline constexpr const char* a_bothHandsUp                      = "\xEE\x84\x81";  // icon_active_bothHandsUp  (U+E101)
inline constexpr const char* a_bow                              = "\xEE\x84\x82";  // icon_active_bow  (U+E102)
inline constexpr const char* a_clamp                            = "\xEE\x84\x83";  // icon_active_clamp  (U+E103)
inline constexpr const char* a_dance1                           = "\xEE\x84\x84";  // icon_active_dance1  (U+E104)
inline constexpr const char* a_dance2                           = "\xEE\x84\x85";  // icon_active_dance2  (U+E105)
inline constexpr const char* a_forwardPush                      = "\xEE\x84\x86";  // icon_active_forwardPush  (U+E106)
inline constexpr const char* a_happy                            = "\xEE\x84\x87";  // icon_active_happy  (U+E107)
inline constexpr const char* a_highFiveCmd                      = "\xEE\x84\x88";  // icon_active_highFiveCmd  (U+E108)
inline constexpr const char* a_hightWave                        = "\xEE\x84\x89";  // icon_active_hightWave  (U+E109)
inline constexpr const char* a_hug                              = "\xEE\x84\x8A";  // icon_active_hug  (U+E10A)
inline constexpr const char* a_jumpForward                      = "\xEE\x84\x8B";  // icon_active_jumpForward  (U+E10B)
inline constexpr const char* a_lieDown                          = "\xEE\x84\x8C";  // icon_active_lieDown  (U+E10C)
inline constexpr const char* a_lowWave                          = "\xEE\x84\x8D";  // icon_active_lowWave  (U+E10D)
inline constexpr const char* a_makeHeartBothHands               = "\xEE\x84\x8E";  // icon_active_makeHeartBothHands  (U+E10E)
inline constexpr const char* a_makeHeartSingleHands             = "\xEE\x84\x8F";  // icon_active_makeHeartSingleHands  (U+E10F)
inline constexpr const char* a_newYear                          = "\xEE\x84\x90";  // icon_active_newYear  (U+E110)
inline constexpr const char* a_pounceForward                    = "\xEE\x84\x91";  // icon_active_pounceForward  (U+E111)
inline constexpr const char* a_refuse                           = "\xEE\x84\x92";  // icon_active_refuse  (U+E112)
inline constexpr const char* a_rollOver                         = "\xEE\x84\x93";  // icon_active_rollOver  (U+E113)
inline constexpr const char* a_shakeHands                       = "\xEE\x84\x94";  // icon_active_shakeHands  (U+E114)
inline constexpr const char* a_showHeart                        = "\xEE\x84\x95";  // icon_active_showHeart  (U+E115)
inline constexpr const char* a_singleHandsUp                    = "\xEE\x84\x96";  // icon_active_singleHandsUp  (U+E116)
inline constexpr const char* a_sitDown                          = "\xEE\x84\x97";  // icon_active_sitDown  (U+E117)
inline constexpr const char* a_stretch                          = "\xEE\x84\x98";  // icon_active_stretch  (U+E118)
inline constexpr const char* a_turnOver                         = "\xEE\x84\x99";  // icon_active_turnOver  (U+E119)
inline constexpr const char* a_turnWave                         = "\xEE\x84\x9A";  // icon_active_turnWave  (U+E11A)
inline constexpr const char* a_ultramanRay                      = "\xEE\x84\x9B";  // icon_active_ultramanRay  (U+E11B)
inline constexpr const char* m_a2_stand                         = "\xEE\x84\x9C";  // icon_model_a2_stand  (U+E11C)
inline constexpr const char* m_b2w_all_terrain                  = "\xEE\x84\x9D";  // icon_model_b2w_all_terrain  (U+E11D)
inline constexpr const char* m_b2w_special                      = "\xEE\x84\x9E";  // icon_model_b2w_special  (U+E11E)
inline constexpr const char* m_batteryLife                      = "\xEE\x84\x9F";  // icon_model_batteryLife  (U+E11F)
inline constexpr const char* m_climb                            = "\xEE\x84\xA0";  // icon_model_climb  (U+E120)
inline constexpr const char* m_climbingStairs                   = "\xEE\x84\xA1";  // icon_model_climbingStairs  (U+E121)
inline constexpr const char* m_combat                           = "\xEE\x84\xA2";  // icon_model_combat  (U+E122)
inline constexpr const char* m_crossStep                        = "\xEE\x84\xA3";  // icon_model_crossStep  (U+E123)
inline constexpr const char* m_damping                          = "\xEE\x84\xA4";  // icon_model_damping  (U+E124)
inline constexpr const char* m_dance_g1                         = "\xEE\x84\xA5";  // icon_model_dance_g1  (U+E125)
inline constexpr const char* m_debug                            = "\xEE\x84\xA6";  // icon_model_debug  (U+E126)
inline constexpr const char* m_freeWalk                         = "\xEE\x84\xA7";  // icon_model_freeWalk  (U+E127)
inline constexpr const char* m_g1_walk                          = "\xEE\x84\xA8";  // icon_model_g1_walk  (U+E128)
inline constexpr const char* m_hand_stand                       = "\xEE\x84\xA9";  // icon_model_hand_stand  (U+E129)
inline constexpr const char* m_keepMoving                       = "\xEE\x84\xAA";  // icon_model_keepMoving  (U+E12A)
inline constexpr const char* m_keepRunning                      = "\xEE\x84\xAB";  // icon_model_keepRunning  (U+E12B)
inline constexpr const char* m_lieUp                            = "\xEE\x84\xAC";  // icon_model_lieUp  (U+E12C)
inline constexpr const char* m_locking                          = "\xEE\x84\xAD";  // icon_model_locking  (U+E12D)
inline constexpr const char* m_monthStart                       = "\xEE\x84\xAE";  // icon_model_monthStart  (U+E12E)
inline constexpr const char* m_pose                             = "\xEE\x84\xAF";  // icon_model_pose  (U+E12F)
inline constexpr const char* m_preparation                      = "\xEE\x84\xB0";  // icon_model_preparation  (U+E130)
inline constexpr const char* m_run                              = "\xEE\x84\xB1";  // icon_model_run  (U+E131)
inline constexpr const char* m_runSideBySide                    = "\xEE\x84\xB2";  // icon_model_runSideBySide  (U+E132)
inline constexpr const char* m_seating                          = "\xEE\x84\xB3";  // icon_model_seating  (U+E133)
inline constexpr const char* m_sideStep                         = "\xEE\x84\xB4";  // icon_model_sideStep  (U+E134)
inline constexpr const char* m_squat                            = "\xEE\x84\xB5";  // icon_model_squat  (U+E135)
inline constexpr const char* m_squatUp                          = "\xEE\x84\xB6";  // icon_model_squatUp  (U+E136)
inline constexpr const char* m_stand                            = "\xEE\x84\xB7";  // icon_model_stand  (U+E137)
inline constexpr const char* m_standActive                      = "\xEE\x84\xB8";  // icon_model_standActive  (U+E138)
inline constexpr const char* m_step                             = "\xEE\x84\xB9";  // icon_model_step  (U+E139)
inline constexpr const char* m_unlock                           = "\xEE\x84\xBA";  // icon_model_unlock  (U+E13A)
inline constexpr const char* m_walk                             = "\xEE\x84\xBB";  // icon_model_walk  (U+E13B)
inline constexpr const char* m_zeroTorque                       = "\xEE\x84\xBC";  // icon_model_zeroTorque  (U+E13C)
}  // namespace ts

}  // namespace icon
}  // namespace go2
